### ISSUE TITLE
IllegalStateException not explicit when no mongo executable

### ISSUE THREAD

**Issue by Lysoun** [4sh/datamaintain#81]
I am using Datamaintain embedded in my project. 
I do not have mongo on my computer and am using a container to store my database with the correct mongo version. When I am launching my server, with Datamaintain enabled, I have this error:

```
java.lang.IllegalStateException: Cannot run program "mongo" (in directory "."): error=2, No such file or directory
	at datamaintain.core.util.ProcessUtilKt.runProcess(ProcessUtil.kt:26)
	at datamaintain.core.util.ProcessUtilKt.runProcess$default(ProcessUtil.kt:12)
	at datamaintain.db.driver.mongo.MongoDriver.executeMongoQuery(MongoDriver.kt:84)
	at datamaintain.db.driver.mongo.MongoDriver.listExecutedScripts(MongoDriver.kt:72)
	at datamaintain.core.step.Pruner.prune(Pruner.kt:12)
	at datamaintain.core.Datamaintain.updateDatabase(Datamaintain.kt:36)
	at com.beclm.base.mongo.DB.launchDataMaintain(MongoRepository.kt:245)
	at com.beclm.core.server.AppModule.mongoClient(AppModule.kt:34)
	at com.beclm.core.server.AppModuleFactoryMachine$4.doNewComponent(AppModuleFactoryMachine.java:80)
	at com.beclm.core.server.AppModuleFactoryMachine$4.doNewComponent(AppModuleFactoryMachine.java:68)
	at restx.factory.StdMachineEngine.newComponent(StdMachineEngine.java:37)
	at restx.factory.Factory.buildAndStore(Factory.java:1249)
	at restx.factory.Factory.buildAndStore(Factory.java:1216)
	at restx.factory.Factory.satisfyBoms(Factory.java:1175)
	at restx.factory.Factory.buildAndStore(Factory.java:1069)
	at restx.factory.Factory.access$600(Factory.java:37)
	at restx.factory.Factory$NameQuery.doFindOne(Factory.java:604)
	at restx.factory.Factory$SingleQuery.doFind(Factory.java:521)
	at restx.factory.Factory$Query.find(Factory.java:448)
	at restx.factory.Factory$ClassQuery.doFind(Factory.java:662)
	at restx.factory.Factory$MultipleQuery.doFindOne(Factory.java:486)
	at restx.factory.Factory$Query.findOne(Factory.java:437)
	at restx.factory.Factory$Query.findOneAsComponent(Factory.java:440)
	at restx.factory.Factory.getComponent(Factory.java:798)
	at restx.RestxMainRouterFactory.newStdRouter(RestxMainRouterFactory.java:555)
	at restx.RestxMainRouterFactory.build(RestxMainRouterFactory.java:380)
	at restx.RestxMainRouterFactory.newInstance(RestxMainRouterFactory.java:75)
	at restx.servlet.RestxMainRouterServlet.init(RestxMainRouterServlet.java:74)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1269)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1182)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1072)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5368)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5660)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1571)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1561)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It happens because there is no mongo executable on my computer but the error is not very user-friendly. The way to solve this problem would be to give a path to a mongo executable to Datamaintain and Datamaintain should throw an error giving a way to solve the problem, to help users.

An exception will be thrown in the pruner, which collects the executed scripts from the database, and in the executor, which tries to run scripts on the database.

**Comment by gonzalt03** [comment]
L'ajout d'un VM options comme celui-ci, ne résout pas le problème :
`
-Ddb.mongo.client.path=/usr/local/Cellar/mongodb-community/4.2.7/bin/
`
